# Generated by Django 5.2.9 on 2025-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="party_name",
            field=models.CharField(
                blank=True,
                help_text="Label for this party/group (e.g., 'Party A', 'Window Side')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seat_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seat number for split billing (1, 2, 3...)",
                null=True,
            ),
        ),
    ]
