# Generated by Django 5.2.9 on 2025-12-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_party_and_seat_number"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="combined_tables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional tables combined for large parties",
                related_name="combined_orders",
                to="tables.table",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary table for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="tables.table",
            ),
        ),
    ]
