# Generated by Django 5.2.9 on 2025-12-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_outlet_alter_businesssettings_accent_color_and_more"),
        ("orders", "0003_add_combined_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this order belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.outlet",
            ),
        ),
    ]
