# Generated by Django 5.2.9 on 2025-12-12 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOnGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Customer must select at least one option",
                    ),
                ),
                (
                    "is_multi_select",
                    models.BooleanField(
                        default=True, help_text="Allow multiple selections"
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of selections (null = unlimited)",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Add-On Group",
                "verbose_name_plural": "Add-On Groups",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_until", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComboMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="combos/"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of individual item prices",
                        max_digits=10,
                    ),
                ),
                (
                    "combo_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted combo price",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_until", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Combo Meal",
                "verbose_name_plural": "Combo Meals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="menu.addongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Add-On",
                "verbose_name_plural": "Add-Ons",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu_items/"),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                        ],
                        default="veg",
                        max_length=10,
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        default=10, help_text="Estimated preparation time in minutes"
                    ),
                ),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="addongroup",
            name="menu_items",
            field=models.ManyToManyField(
                blank=True, related_name="addon_groups", to="menu.menuitem"
            ),
        ),
        migrations.CreateModel(
            name="MenuItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_default", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Variant",
                "verbose_name_plural": "Menu Item Variants",
                "ordering": ["price"],
                "unique_together": {("menu_item", "name")},
            },
        ),
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.combomeal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menuitem"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu.menuitemvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Item",
                "verbose_name_plural": "Combo Items",
            },
        ),
    ]
