# Generated by Django 5.2.9 on 2025-12-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_outlet_alter_businesssettings_accent_color_and_more"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="core.outlet",
            ),
        ),
    ]
