# Generated by Django 5.2.9 on 2025-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_outlet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("outlet_manager", "Outlet Manager"),
                    ("staff_cashier", "Cashier"),
                    ("staff_kitchen", "Kitchen Staff"),
                    ("waiter", "Waiter"),
                ],
                default="waiter",
                help_text="User role determines access permissions",
                max_length=20,
            ),
        ),
    ]
