# Generated by Django 5.0.1 on 2025-12-12 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_add_combined_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Licenses'), ('equipment', 'Equipment'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_drawers_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_drawers_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Drawer',
                'verbose_name_plural': 'Cash Drawers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='finance.cashdrawer')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashier Shift',
                'verbose_name_plural': 'Cashier Shifts',
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale Payment'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('expense', 'Expense Payment'), ('petty_cash', 'Petty Cash'), ('float', 'Float Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.cashdrawer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='orders.payment')),
                ('cashier_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashiershift')),
            ],
            options={
                'verbose_name': 'Cash Drawer Transaction',
                'verbose_name_plural': 'Cash Drawer Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expense_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='paid', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('cash_drawer_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.cashdrawertransaction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
