# Generated by Django 5.0.1 on 2025-12-12 11:00

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Seed default expense categories."""
    ExpenseCategory = apps.get_model("finance", "ExpenseCategory")

    defaults = [
        ("Rent", "rent", "Monthly rent and lease payments"),
        ("Utilities", "utilities", "Electricity, water, gas, internet"),
        ("Salaries", "salaries", "Staff wages and salaries"),
        ("Supplies", "supplies", "Office and kitchen supplies"),
        ("Maintenance", "maintenance", "Repairs and maintenance"),
        ("Marketing", "marketing", "Advertising and promotions"),
        ("Insurance", "insurance", "Business insurance premiums"),
        ("Taxes & Licenses", "taxes", "Taxes, permits, and licenses"),
        ("Equipment", "equipment", "Equipment purchases and rentals"),
    ]

    for i, (name, cat_type, description) in enumerate(defaults):
        ExpenseCategory.objects.create(
            name=name,
            category_type=cat_type,
            description=description,
            is_default=True,
            is_active=True,
            display_order=i,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded categories."""
    ExpenseCategory = apps.get_model("finance", "ExpenseCategory")
    ExpenseCategory.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
