# Generated by Django 5.2.9 on 2025-12-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_outlet_alter_businesssettings_accent_color_and_more"),
        ("finance", "0002_seed_expense_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashdrawer",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this cash drawer belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_drawers",
                to="core.outlet",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this expense belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="core.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="cashdrawer",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="cashdrawer",
            unique_together={("outlet", "date")},
        ),
    ]
