# Generated by Django 5.2.9 on 2025-12-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="Coffee Shop", max_length=200),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("gst_number", models.CharField(blank=True, max_length=50)),
                ("fssai_number", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                (
                    "receipt_header",
                    models.TextField(
                        blank=True, help_text="Text to display at top of receipts"
                    ),
                ),
                (
                    "receipt_footer",
                    models.TextField(
                        blank=True, help_text="Text to display at bottom of receipts"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Settings",
                "verbose_name_plural": "Business Settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "sms_order_ready",
                    models.BooleanField(
                        default=True, help_text="Send SMS when order is ready"
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("whatsapp_order_confirmation", models.BooleanField(default=False)),
                ("whatsapp_order_ready", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=False)),
                ("email_daily_report", models.BooleanField(default=False)),
                ("daily_report_email", models.EmailField(blank=True, max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
        migrations.CreateModel(
            name="OrderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_accept_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically accept new orders without manual confirmation",
                    ),
                ),
                (
                    "default_preparation_time",
                    models.PositiveIntegerField(
                        default=10, help_text="Default preparation time in minutes"
                    ),
                ),
                ("order_number_prefix", models.CharField(default="ORD", max_length=10)),
                (
                    "daily_order_reset",
                    models.BooleanField(
                        default=True, help_text="Reset order numbers daily"
                    ),
                ),
                (
                    "require_phone_takeaway",
                    models.BooleanField(
                        default=True,
                        help_text="Require phone number for takeaway orders",
                    ),
                ),
                ("takeaway_token_prefix", models.CharField(default="T", max_length=5)),
                (
                    "allow_qr_ordering",
                    models.BooleanField(
                        default=True, help_text="Allow customers to order via QR code"
                    ),
                ),
                (
                    "require_customer_info_qr",
                    models.BooleanField(
                        default=False, help_text="Require name/phone for QR orders"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order Settings",
                "verbose_name_plural": "Order Settings",
            },
        ),
        migrations.CreateModel(
            name="PrinterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_printer_enabled", models.BooleanField(default=False)),
                ("receipt_printer_name", models.CharField(blank=True, max_length=100)),
                (
                    "receipt_printer_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "receipt_auto_print",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically print receipt on payment",
                    ),
                ),
                ("kot_printer_enabled", models.BooleanField(default=False)),
                ("kot_printer_name", models.CharField(blank=True, max_length=100)),
                ("kot_printer_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "kot_auto_print",
                    models.BooleanField(
                        default=False, help_text="Automatically print KOT on order"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Printer Settings",
                "verbose_name_plural": "Printer Settings",
            },
        ),
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="Central GST rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="State GST rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "service_charge_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Service charge rate (%)",
                        max_digits=5,
                    ),
                ),
                ("service_charge_enabled", models.BooleanField(default=False)),
                (
                    "tax_inclusive_pricing",
                    models.BooleanField(
                        default=False, help_text="If True, menu prices include tax"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Settings",
                "verbose_name_plural": "Tax Settings",
            },
        ),
    ]
