# Generated by Django 5.2.9 on 2025-12-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="accent_color",
            field=models.CharField(
                default="#dc2626",
                help_text="Accent color for highlights (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="default_theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System Default"),
                ],
                default="light",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="login_bg_gradient_end",
            field=models.CharField(
                default="#dc2626",
                help_text="Login page gradient end color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="login_bg_gradient_start",
            field=models.CharField(
                default="#f59e0b",
                help_text="Login page gradient start color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="login_subtitle",
            field=models.CharField(default="Sign in to your account", max_length=200),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="login_welcome_text",
            field=models.CharField(
                default="Welcome back!",
                help_text="Login page welcome message",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                help_text="Logo for dark backgrounds",
                null=True,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="primary_color",
            field=models.CharField(
                default="#f59e0b", help_text="Primary brand color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="secondary_color",
            field=models.CharField(
                default="#ea580c", help_text="Secondary brand color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="sidebar_active_color",
            field=models.CharField(
                default="#6366f1",
                help_text="Active menu item color (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="sidebar_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Sidebar background color (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="sidebar_text_color",
            field=models.CharField(
                default="#374151", help_text="Sidebar text color (hex)", max_length=7
            ),
        ),
    ]
