# Generated by Django 5.2.9 on 2025-12-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_theme_customization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique outlet code (e.g., 'NYC01', 'LA02')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "currency_code",
                    models.CharField(
                        default="INR",
                        help_text="ISO 4217 currency code (e.g., 'INR', 'USD', 'EUR')",
                        max_length=3,
                    ),
                ),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("before", "Before amount (e.g., $100)"),
                            ("after", "After amount (e.g., 100€)"),
                        ],
                        default="before",
                        max_length=10,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="outlet_logos/"),
                ),
                (
                    "receipt_header",
                    models.TextField(
                        blank=True, help_text="Text to display at top of receipts"
                    ),
                ),
                (
                    "receipt_footer",
                    models.TextField(
                        blank=True, help_text="Text to display at bottom of receipts"
                    ),
                ),
                (
                    "operating_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operating hours per day of the week",
                    ),
                ),
                ("tax_enabled", models.BooleanField(default=True)),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="Central GST rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        help_text="State GST rate (%)",
                        max_digits=5,
                    ),
                ),
                ("service_charge_enabled", models.BooleanField(default=False)),
                (
                    "service_charge_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Service charge rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_inclusive_pricing",
                    models.BooleanField(
                        default=False, help_text="If True, menu prices include tax"
                    ),
                ),
                (
                    "order_prefix",
                    models.CharField(
                        default="ORD",
                        help_text="Prefix for order numbers",
                        max_length=10,
                    ),
                ),
                (
                    "auto_accept_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically accept new orders without manual confirmation",
                    ),
                ),
                (
                    "default_prep_time",
                    models.PositiveIntegerField(
                        default=10, help_text="Default preparation time in minutes"
                    ),
                ),
                (
                    "allow_qr_ordering",
                    models.BooleanField(
                        default=True, help_text="Allow customers to order via QR code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Outlet",
                "verbose_name_plural": "Outlets",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="accent_color",
            field=models.CharField(
                default="#ec4899",
                help_text="Accent color for highlights (hex)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="login_bg_gradient_end",
            field=models.CharField(
                default="#8b5cf6",
                help_text="Login page gradient end color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="login_bg_gradient_start",
            field=models.CharField(
                default="#6366f1",
                help_text="Login page gradient start color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="primary_color",
            field=models.CharField(
                default="#6366f1", help_text="Primary brand color (hex)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="secondary_color",
            field=models.CharField(
                default="#8b5cf6", help_text="Secondary brand color (hex)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="sidebar_color",
            field=models.CharField(
                default="#0f172a",
                help_text="Sidebar background color (hex)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="sidebar_text_color",
            field=models.CharField(
                default="#94a3b8", help_text="Sidebar text color (hex)", max_length=7
            ),
        ),
    ]
