# Generated by Django 5.2.9 on 2025-12-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("payu", "PayU"),
                            ("manual", "Manual Entry"),
                        ],
                        default="razorpay",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_key_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay Key ID (starts with rzp_)",
                        max_length=100,
                    ),
                ),
                (
                    "razorpay_key_secret",
                    models.CharField(
                        blank=True, help_text="Razorpay Key Secret", max_length=100
                    ),
                ),
                (
                    "razorpay_webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay Webhook Secret for signature verification",
                        max_length=100,
                    ),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        help_text="UPI ID for static QR (e.g., shop@paytm)",
                        max_length=100,
                    ),
                ),
                (
                    "upi_merchant_name",
                    models.CharField(
                        blank=True,
                        help_text="Merchant name to display on UPI apps",
                        max_length=100,
                    ),
                ),
                (
                    "is_live_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Use live API keys (uncheck for test mode)",
                    ),
                ),
                (
                    "auto_verify_payments",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically verify payment status via API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Settings",
                "verbose_name_plural": "Payment Settings",
            },
        ),
        migrations.CreateModel(
            name="RazorpayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=100, unique=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
                ("razorpay_signature", models.CharField(blank=True, max_length=200)),
                ("amount", models.PositiveIntegerField(help_text="Amount in paise")),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("qr_code_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_orders",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Razorpay Order",
                "verbose_name_plural": "Razorpay Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
