# Generated by Django 5.2.9 on 2025-12-12 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Table number (e.g., T1, T2, A1)", max_length=10
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name (e.g., Window Seat)",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Maximum seating capacity"),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("2_seater", "2 Seater"),
                            ("4_seater", "4 Seater"),
                            ("6_seater", "6 Seater"),
                            ("8_seater", "8 Seater"),
                            ("booth", "Booth"),
                            ("round", "Round"),
                            ("bar", "Bar Stool"),
                        ],
                        default="4_seater",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("billed", "Billed"),
                            ("cleaning", "Cleaning"),
                            ("reserved", "Reserved"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("position_x", models.PositiveIntegerField(default=0)),
                ("position_y", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="tables.floor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["floor", "number"],
                "unique_together": {("floor", "number")},
            },
        ),
        migrations.CreateModel(
            name="TableSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                ("guest_count", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tables.table",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Session",
                "verbose_name_plural": "Table Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
