# Generated by Django 5.2.9 on 2025-12-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_outlet_alter_businesssettings_accent_color_and_more"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycategory",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_categories",
                to="core.outlet",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this purchase order is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="core.outlet",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                help_text="Outlet this supplier is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="core.outlet",
            ),
        ),
        migrations.AlterField(
            model_name="inventorycategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="inventorycategory",
            unique_together={("outlet", "name")},
        ),
    ]
